#!/bin/bash
#
# wlanpi-fpms2 prerm script
#
set -e

# Stop and disable services before removing
if [ -d /run/systemd/system ]; then
    systemctl stop  wlanpi-fpms2-screen.service 2>/dev/null || true
    systemctl stop  wlanpi-fpms2.service        2>/dev/null || true
    systemctl disable wlanpi-fpms2-screen.service 2>/dev/null || true
    systemctl disable wlanpi-fpms2.service        2>/dev/null || true
fi

#DEBHELPER#

exit 0
